import Head from "next/head";
import { Inter } from "@next/font/google";
///
// import styles from "@/styles/Home.module.css";
///
import NoteAppContextProvider from "../store/notes_context";
///
import Layout from "../components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NoteAppContextProvider>
        {/* <main className={styles.main}>
          <div className={styles.description}> */}
        <Layout />
        {/* </div>
        </main> */}
      </NoteAppContextProvider>
    </>
  );
}
