import Head from "next/head";
///
import NoteAppContextProvider from "../store/notes_context";
///
import Layout from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Toma Notas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NoteAppContextProvider>
        <Layout />
      </NoteAppContextProvider>
    </>
  );
}
